/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kasirrpl;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author LWNOVO
 */
public class Menu extends javax.swing.JFrame {
    private int level_id;
    private Connection connection;
    private PreparedStatement statement;
    private ResultSet rs;
    private String username;
    private String nama_user;
    connector k = new connector();
    /**
     * Creates new form Menu
     */
    public Menu(int level_id, String username) {
        initComponents();
        this.level_id = level_id;
        this.username = username;
        k.connection();
        this.nama_user = getNamaUser(username);
        configureMenu();
    }
    
     private String getNamaUser(String username) {
        String nama_user = "";
        try {
            this.statement = k.connection().prepareStatement("SELECT nama_user FROM user WHERE username = ?");
            statement.setString(1, username);
            this.rs = this.statement.executeQuery();
            if (rs.next()) {
                nama_user = rs.getString("nama_user");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        return nama_user;
    }
      
      private void configureMenu() {
        jLabelnama.setText(nama_user + " !");
        switch (level_id) {
            case 1:
                jButtonTransaksi.setEnabled(true);
                ButtonItem.setEnabled(true);
                ButtonLaporan.setEnabled(true);
                ButtonRegis.setEnabled(true);
                break;
            case 2:
                jButtonTransaksi.setEnabled(true);
                ButtonItem.setEnabled(true);
                break;
            case 3:
                ButtonItem.setEnabled(true);
                ButtonLaporan.setEnabled(true);
//              ButtonRegis.setEnabled(true);
                break;
            default:
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelnama = new javax.swing.JLabel();
        jButtonTransaksi = new javax.swing.JButton();
        ButtonRegis = new javax.swing.JButton();
        ButtonLaporan = new javax.swing.JButton();
        ButtonItem = new javax.swing.JButton();
        ButtonLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("SELAMAT DATANG,");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kasirrpl/_6dc3f85c-3cf3-46ca-a384-b75bde5c4463.jpg"))); // NOI18N
        jLabel4.setText("masukin picture");
        jLabel4.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("\"Kenyamanan dan Kebutuhan Pelanggan adalah yang nomer 1\"");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Silahkan pilih menu yang ingin dilakukan !");

        jLabelnama.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabelnama.setForeground(new java.awt.Color(51, 153, 255));
        jLabelnama.setText("GUEST");

        jButtonTransaksi.setBackground(new java.awt.Color(51, 153, 255));
        jButtonTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButtonTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTransaksi.setText("Transaksi");
        jButtonTransaksi.setEnabled(false);
        jButtonTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTransaksiActionPerformed(evt);
            }
        });

        ButtonRegis.setBackground(new java.awt.Color(51, 153, 255));
        ButtonRegis.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        ButtonRegis.setForeground(new java.awt.Color(255, 255, 255));
        ButtonRegis.setText("Registrasi User");
        ButtonRegis.setEnabled(false);
        ButtonRegis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRegisActionPerformed(evt);
            }
        });

        ButtonLaporan.setBackground(new java.awt.Color(51, 153, 255));
        ButtonLaporan.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        ButtonLaporan.setForeground(new java.awt.Color(255, 255, 255));
        ButtonLaporan.setText("Cetak Laporan");
        ButtonLaporan.setEnabled(false);
        ButtonLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLaporanActionPerformed(evt);
            }
        });

        ButtonItem.setBackground(new java.awt.Color(51, 153, 255));
        ButtonItem.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        ButtonItem.setForeground(new java.awt.Color(255, 255, 255));
        ButtonItem.setText("Kelola Item ");
        ButtonItem.setEnabled(false);
        ButtonItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonItemActionPerformed(evt);
            }
        });

        ButtonLogout.setBackground(new java.awt.Color(255, 51, 51));
        ButtonLogout.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        ButtonLogout.setForeground(new java.awt.Color(255, 255, 255));
        ButtonLogout.setText("LOGOUT");
        ButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonRegis, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonItem, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelnama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(223, 223, 223)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(ButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelnama, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(33, 33, 33)
                        .addComponent(jButtonTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonItem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(ButtonRegis, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(195, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTransaksiActionPerformed
        MenuTransaksi trans = new MenuTransaksi(level_id, username);
        trans.setLocationRelativeTo(null);
        trans.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTransaksiActionPerformed

    private void ButtonRegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRegisActionPerformed
        MenuRegistrasi regis = new MenuRegistrasi(level_id, username);
        regis.setLocationRelativeTo(null);
        regis.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonRegisActionPerformed

    private void ButtonLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLaporanActionPerformed
        Laporan laporan = new Laporan(level_id, username);
        laporan.setLocationRelativeTo(null);
        laporan.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonLaporanActionPerformed

    private void ButtonItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonItemActionPerformed
        MenuItem item = new MenuItem(level_id, username);
        item.setLocationRelativeTo(null);
        item.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonItemActionPerformed

    private void ButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLogoutActionPerformed
        int pilih = JOptionPane.showConfirmDialog(null,
                    "Ingin Logout sekarang ?",
                    "Logout", JOptionPane.YES_NO_OPTION );
        if (pilih == JOptionPane.YES_OPTION){
                Login login = new Login();
                login.setLocationRelativeTo(null);
                login.setVisible(true);
                this.setVisible(false);
                ButtonItem.setEnabled(false);
                ButtonLaporan.setEnabled(false);
                ButtonRegis.setEnabled(false);
            }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                int level_id = LoginService.getLoggedInLevelId();
                String username = LoginService.getLoggedInUsername();
                new Menu(level_id, username).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton ButtonItem;
    public javax.swing.JButton ButtonLaporan;
    public javax.swing.JButton ButtonLogout;
    public javax.swing.JButton ButtonRegis;
    private javax.swing.JButton jButtonTransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabelnama;
    // End of variables declaration//GEN-END:variables
}
